GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
   "title": "Harry Potter"
}
clase 120
install json-server
y la extension rest client en visual